
title: Sudut Nirwana
description: "Koleksi chord gitar dan tablature lagu terlengkap untuk pemula. Update setiap hari dengan fitur auto-scroll dan transpose nada akurat."
baseurl: ""
url: "https://sudutnirwana.com"

# Tambahan untuk membantu SEO Jekyll
permalink: /:title/
markdown: kramdown
theme: minima # atau biarkan kosong jika kamu pakai CSS sendiri
exclude: [Gemfile, Gemfile.lock, node_modules]
